global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    metrics_path: "/metrics"
    static_configs:
      - targets: ['backend:4000']
    params:
      modules: [
        'process_stats',
        'network_stats',
        'system_info',
        'job_queue',
        'directory_info',
        'printer_objects',
        'history',
      ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: backend:4000